// <auto-generated />
using System;
using DesafioTDD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioTDD.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220505142756_CreateIdentitySchema")]
    partial class CreateIdentitySchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("DesafioTDD.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Administradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Senha = "admin",
                            User = "admin"
                        });
                });

            modelBuilder.Entity("DesafioTDD.Models.Caixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ced10")
                        .HasColumnType("int");

                    b.Property<int>("Ced100")
                        .HasColumnType("int");

                    b.Property<int>("Ced20")
                        .HasColumnType("int");

                    b.Property<int>("Ced50")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Caixas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ced10 = 500,
                            Ced100 = 500,
                            Ced20 = 500,
                            Ced50 = 500,
                            Total = 90000.0
                        });
                });

            modelBuilder.Entity("DesafioTDD.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<double>("Saldo")
                        .HasColumnType("double");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Cartoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = "1895556789473233",
                            Saldo = 5000.0,
                            Senha = "1234",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Numero = "3567556789473233",
                            Saldo = 2000.0,
                            Senha = "1234",
                            Status = true
                        });
                });

            modelBuilder.Entity("DesafioTDD.Models.Extrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CartaoId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.ToTable("Extratos");
                });

            modelBuilder.Entity("DesafioTDD.Models.Extrato", b =>
                {
                    b.HasOne("DesafioTDD.Models.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId");

                    b.Navigation("Cartao");
                });
#pragma warning restore 612, 618
        }
    }
}
